name: camwork_flutter
description: Professional Photo Processing Suite in Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  crypto: ^3.0.0
  pdf: ^3.8.1
  printing: ^5.9.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
