# pubspec.yaml
name: camwork_flutter
description: Professional Photo Processing Suite in Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization support
  flutter_localizations:
    sdk: flutter

  path: ^1.8.0
  crypto: ^3.0.0
  pdf: ^3.8.1
  printing: ^5.9.0
  shared_preferences: ^2.0.15
  file_picker: ^6.0.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.1.5
  logging: ^1.1.0
  win32: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
